# Generated by Django 3.1.13 on 2021-09-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_auto_20210830_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='XY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
            ],
        ),
    ]
