# Generated by Django 3.1.13 on 2021-08-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_auto_20210830_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sns',
            field=models.CharField(choices=[('NAVER', 'NAVER'), ('INSTAGRAM', 'INSTAGRAM')], default='INSTAGRAM', max_length=100),
        ),
        migrations.AddField(
            model_name='data',
            name='sns_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
